/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailapp.gui;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import mailapp.logicCode.ComposeGUI;

/**
 *
 * @author محمد
 */
public class AddAttachmentFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAttachmentFrame
     */
    public static Inbox in;
    
    public AddAttachmentFrame(JFrame frame) {
        try {
            in = (Inbox) frame;
            initComponents();
            this.setLocationRelativeTo(null);
            ComposeGUI comp = new ComposeGUI();
            if (in.attachments.size() == 0) {
                attachmentpic.setVisible(true);
            } else {
                comp.loadAttachment(in.attachments, this);
                jTextField2.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAttachmentsPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        attach2 = new javax.swing.JLabel();
        attach3 = new javax.swing.JLabel();
        attach4 = new javax.swing.JLabel();
        attach5 = new javax.swing.JLabel();
        attach6 = new javax.swing.JLabel();
        attach1 = new javax.swing.JLabel();
        na1 = new javax.swing.JLabel();
        na2 = new javax.swing.JLabel();
        na3 = new javax.swing.JLabel();
        na4 = new javax.swing.JLabel();
        na5 = new javax.swing.JLabel();
        na6 = new javax.swing.JLabel();
        attachmentpic = new javax.swing.JLabel();
        backgrounAddRecivers1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addAttachmentsPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        addAttachmentsPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 273, 63, 38));

        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 367, 93, 38));

        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 263, 135, 55));

        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 264, 137, 54));

        error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 90, 20));

        attach2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach2MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 110, 70));

        attach3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach3MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 110, 70));

        attach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach4MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, 70));

        attach5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach5MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 110, 70));

        attach6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach6MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, 70));

        attach1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach1MouseClicked(evt);
            }
        });
        addAttachmentsPanel1.add(attach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 110, 70));

        na1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 110, 15));

        na2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 110, 15));

        na3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 110, 15));

        na4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 15));

        na5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 110, 15));

        na6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addAttachmentsPanel1.add(na6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 15));

        attachmentpic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/Attachment Word.png"))); // NOI18N
        addAttachmentsPanel1.add(attachmentpic, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 80, -1, 90));

        backgrounAddRecivers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/addAttach1.png"))); // NOI18N
        addAttachmentsPanel1.add(backgrounAddRecivers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        getContentPane().add(addAttachmentsPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        //jTextArea3.setText("");
        jTextField2.setText("");
        error.setText("");
        in.addattachmentcounter++;
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        ComposeGUI setup1 = new ComposeGUI();
        try {
            if (setup1.removeAttachment(in.attachments, Integer.parseInt(jTextField2.getText()), in.composeAttach)) {
                
                jTextField2.setText("");
                error.setText("");
                //jTextArea3.setText(setup1.showAttach(in.attachments));
                if (in.attachments.size() == 0) {
                    attachmentpic.setVisible(true);
                    attach1.setVisible(false);
                    na1.setVisible(false);
                } else {
                    setup1.loadAttachment(in.attachments, this);
                    attachmentpic.setVisible(false);
                }
                //System.out.println(in.attachments.size());
            } else {
                error.setText("Wrong index");
            }
        } catch (Exception e) {
            error.setText("Wrong index");
            
        }

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        if (in.attachments.size() != 6) {
            JFileChooser f = new JFileChooser();
            
            ComposeGUI compose = new ComposeGUI();
            int result = f.showDialog(this, "select files");
            File fi = f.getSelectedFile();
            if (fi != null && result == JFileChooser.APPROVE_OPTION) {
                compose.addAttachment(in.attachments, fi.getPath(), in.composeAttach);
                try {
                    //jTextArea3.setText(compose.showAttach(in.attachments));
                    attachmentpic.setVisible(false);
                    compose.loadAttachment(in.attachments, this);
                    error.setText("");
                    jTextField2.setText("");
                   
                } catch (IOException ex) {
                    Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        } else {
            error.setText("Maximum 6");
        }

    }//GEN-LAST:event_jLabel12MouseClicked

    private void attach1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach1MouseClicked
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(0));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach1MouseClicked

    private void attach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach2MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(1));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach2MouseClicked

    private void attach3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach3MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(2));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach3MouseClicked

    private void attach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach4MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(3));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach4MouseClicked

    private void attach5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach5MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(4));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach5MouseClicked

    private void attach6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach6MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open((File) in.attachments.get(5));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAttachmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAttachmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAttachmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAttachmentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAttachmentFrame(in).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addAttachmentsPanel1;
    public static javax.swing.JLabel attach1;
    public static javax.swing.JLabel attach2;
    public static javax.swing.JLabel attach3;
    public static javax.swing.JLabel attach4;
    public static javax.swing.JLabel attach5;
    public static javax.swing.JLabel attach6;
    public static javax.swing.JLabel attachmentpic;
    private javax.swing.JLabel backgrounAddRecivers1;
    public javax.swing.JLabel error;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel na1;
    public static javax.swing.JLabel na2;
    public static javax.swing.JLabel na3;
    public static javax.swing.JLabel na4;
    public static javax.swing.JLabel na5;
    public static javax.swing.JLabel na6;
    // End of variables declaration//GEN-END:variables
}
