/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailapp.gui;

import java.awt.Color;
import javax.swing.JFrame;
import mailapp.logicCode.ComposeGUI;

/**
 *
 * @author محمد
 */
public class AddRecframe extends javax.swing.JFrame {

    /**
     * Creates new form AddRecframe
     */
    ComposeGUI setup1 = new ComposeGUI();
    public static Inbox in;

    public AddRecframe(JFrame frame) {
        in = (Inbox) frame;
        initComponents();
        jTextField1.setBackground(new Color(0, 0, 0, 0));
        jTextArea2.setBackground(new Color(0, 0, 0, 0));
        jScrollPane3.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        jTextArea2.setText("");
        jTextField1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addRecieversPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        backgrounAddRecivers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addRecieversPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setOpaque(false);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setBorder(null);
        jTextArea2.setOpaque(false);
        jScrollPane3.setViewportView(jTextArea2);

        addRecieversPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 40, 480, 140));

        jTextField1.setBackground(new java.awt.Color(51, 51, 255));
        jTextField1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        addRecieversPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 277, 55, 30));

        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        addRecieversPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 367, 93, 38));

        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        addRecieversPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 268, 126, 52));

        error.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 0));
        error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addRecieversPanel.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 120, 30));

        backgrounAddRecivers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/add recievers.png"))); // NOI18N
        addRecieversPanel.add(backgrounAddRecivers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        getContentPane().add(addRecieversPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jTextArea2.setText("");
        jTextField1.setText("");
        // Inbox in = new Inbox();
        in.addcounter++;
        this.dispose();

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        //Inbox in = new Inbox();
        try {
            if (setup1.removeName(in.recieversNames, Integer.parseInt(jTextField1.getText()))) {
                jTextField1.setText("");
                error.setText("");
                jTextArea2.setText(setup1.showNames(in.recieversNames));
            } else {
                error.setText("Wrong index");
            }
        } catch (Exception e) {
            error.setText("Wrong index");

        }

    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRecframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRecframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRecframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRecframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRecframe(in).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addRecieversPanel;
    private javax.swing.JLabel backgrounAddRecivers;
    public javax.swing.JLabel error;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTextArea jTextArea2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
