/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailapp.gui;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import mailapp.logicCode.App;
import mailapp.logicCode.SignUp;

/**
 *
 * @author arabtech
 */
public class Home extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    int creditsCount = 0;

    /**
     * Creates new form Home
     */
    public Home() throws IOException {
        initComponents();
        userEmailSI.setBackground(new Color(0, 0, 0, 20));
        passwordSI.setBackground(new Color(0, 0, 0, 20));
        userEmailSU.setBackground(new Color(0, 0, 0, 20));
        passwordSU.setBackground(new Color(0, 0, 0, 20));
        ans.setBackground(new Color(0, 0, 0, 20));
        ques.setBackground(new Color(0, 0, 0, 20));
        userName.setBackground(new Color(0, 0, 0, 20));
        userEmailSI.setText(null);
        passwordSI.setText(null);
        signUpPanel.setVisible(false);
        File f = new File("server\\users");
        f.mkdirs();
        File r = new File("server\\users\\users.txt");
        BufferedWriter bfw = new BufferedWriter(new FileWriter(r, true));
        bfw.close();
        jPanel1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        close2 = new javax.swing.JLabel();
        minimize1 = new javax.swing.JLabel();
        dragFrame = new javax.swing.JLabel();
        toLogin = new javax.swing.JLabel();
        userEmailSU = new javax.swing.JTextField();
        userName = new javax.swing.JTextField();
        ans = new javax.swing.JTextField();
        ques = new javax.swing.JTextField();
        passwordSU = new javax.swing.JPasswordField();
        signUpbtn = new javax.swing.JLabel();
        credits1 = new javax.swing.JLabel();
        backgroundSU = new javax.swing.JLabel();
        logInPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userEmailSI = new javax.swing.JTextField();
        passwordSI = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JLabel();
        toSignUp = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        close1 = new javax.swing.JLabel();
        dragFrame1 = new javax.swing.JLabel();
        userManual = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        forgetPass = new javax.swing.JLabel();
        backgroundSI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 295, 113, 45));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/credits.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -2, 525, 360));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 520, -1));

        signUpPanel.setPreferredSize(new java.awt.Dimension(1130, 727));
        signUpPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        signUpPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 588, 188, 66));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        signUpPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 680, 520, 40));

        close2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close2MouseClicked(evt);
            }
        });
        signUpPanel.add(close2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 3, 30, 29));

        minimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize1MouseClicked(evt);
            }
        });
        signUpPanel.add(minimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1023, 3, 30, 29));

        dragFrame.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dragFrame.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragFrameMouseDragged(evt);
            }
        });
        dragFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragFrameMousePressed(evt);
            }
        });
        signUpPanel.add(dragFrame, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1120, 35));

        toLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toLoginMouseClicked(evt);
            }
        });
        signUpPanel.add(toLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 45, 110, 70));

        userEmailSU.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        userEmailSU.setForeground(new java.awt.Color(255, 255, 255));
        userEmailSU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userEmailSU.setBorder(null);
        userEmailSU.setOpaque(false);
        signUpPanel.add(userEmailSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 380, 40));

        userName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userName.setBorder(null);
        userName.setOpaque(false);
        signUpPanel.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 380, 40));

        ans.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        ans.setForeground(new java.awt.Color(255, 255, 255));
        ans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ans.setBorder(null);
        ans.setOpaque(false);
        signUpPanel.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 380, 40));

        ques.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        ques.setForeground(new java.awt.Color(255, 255, 255));
        ques.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ques.setBorder(null);
        ques.setOpaque(false);
        signUpPanel.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 380, 40));

        passwordSU.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        passwordSU.setForeground(new java.awt.Color(255, 255, 255));
        passwordSU.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordSU.setBorder(null);
        passwordSU.setOpaque(false);
        passwordSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSUActionPerformed(evt);
            }
        });
        signUpPanel.add(passwordSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 380, 40));

        signUpbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signUpbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpbtnMouseClicked(evt);
            }
        });
        signUpPanel.add(signUpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 650, 154, 40));

        credits1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credits1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                credits1MouseClicked(evt);
            }
        });
        signUpPanel.add(credits1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 588, 146, 66));

        backgroundSU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/signUp4.jpg"))); // NOI18N
        backgroundSU.setText("jLabel1");
        signUpPanel.add(backgroundSU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, 1130, 730));

        jLayeredPane1.add(signUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 730));

        logInPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logInPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 410, 40));

        userEmailSI.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        userEmailSI.setForeground(new java.awt.Color(255, 255, 255));
        userEmailSI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userEmailSI.setBorder(null);
        userEmailSI.setOpaque(false);
        logInPanel.add(userEmailSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 380, 40));

        passwordSI.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        passwordSI.setForeground(new java.awt.Color(255, 255, 255));
        passwordSI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordSI.setBorder(null);
        passwordSI.setOpaque(false);
        passwordSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSIActionPerformed(evt);
            }
        });
        logInPanel.add(passwordSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 380, 40));

        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        logInPanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 467, 150, 40));

        toSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toSignUpMouseClicked(evt);
            }
        });
        logInPanel.add(toSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 54, 140, 60));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        logInPanel.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1023, 3, 30, 29));

        close1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close1MouseClicked(evt);
            }
        });
        logInPanel.add(close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 3, 30, 29));

        dragFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dragFrame1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragFrame1MouseDragged(evt);
            }
        });
        dragFrame1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragFrame1MousePressed(evt);
            }
        });
        logInPanel.add(dragFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1120, 35));

        userManual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userManual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userManualMouseClicked(evt);
            }
        });
        logInPanel.add(userManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 588, 188, 66));

        credits.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        credits.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditsMouseClicked(evt);
            }
        });
        logInPanel.add(credits, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 588, 146, 66));

        forgetPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPassMouseClicked(evt);
            }
        });
        logInPanel.add(forgetPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 566, 230, 30));

        backgroundSI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/signIn5.jpg"))); // NOI18N
        logInPanel.add(backgroundSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -5, -1, 730));

        jLayeredPane1.add(logInPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 730));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        App a = new App();
        char[] pass = passwordSI.getPassword();
        String passStr = "";
        for (int i = 0; i < pass.length; i++) {
            passStr += pass[i];
        }
        if (a.signin(userEmailSI.getText(), passStr)) {
            try {
                Inbox in = new Inbox();
                in.setVisible(true);
                in.setLocationRelativeTo(null);
                this.dispose();
            } catch (IOException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            jLabel1.setText("WRONG EMAIL OR PASSWORD");
        }


    }//GEN-LAST:event_loginBtnMouseClicked

    private void toLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toLoginMouseClicked
        signUpPanel.setVisible(false);
        logInPanel.setVisible(true);
    }//GEN-LAST:event_toLoginMouseClicked

    private void toSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toSignUpMouseClicked
        logInPanel.setVisible(false);
        signUpPanel.setVisible(true);
    }//GEN-LAST:event_toSignUpMouseClicked

    private void passwordSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSIActionPerformed

    private void close1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close1MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void close2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_close2MouseClicked

    private void minimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize1MouseClicked
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_minimize1MouseClicked

    private void passwordSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSUActionPerformed

    private void dragFrameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragFrameMouseDragged

    private void dragFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrameMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragFrameMousePressed

    private void dragFrame1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrame1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_dragFrame1MouseDragged

    private void dragFrame1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragFrame1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_dragFrame1MousePressed

    private void forgetPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPassMouseClicked
        ForgetPasswordFrame f = new ForgetPasswordFrame();
        f.setVisible(true);
        f.setLocationRelativeTo(null);

    }//GEN-LAST:event_forgetPassMouseClicked

    private void signUpbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpbtnMouseClicked
        App a = new App();
        SignUp sU = new SignUp();
        if (userName.getText().length() == 0 || userEmailSU.getText().length() == 0 || passwordSU.getPassword().length == 0 || ques.getText().length() == 0 || ans.getText().length() == 0) {
            jLabel2.setText("There's an Empty Field");
        } else {
            char[] pass = passwordSU.getPassword();
            String passStr = "";
            for (int i = 0; i < pass.length; i++) {
                passStr += pass[i];
            }
            String[] arr = userEmailSU.getText().split("@");
            if (arr.length == 2 && arr[1].equalsIgnoreCase("yallamail.com")) {
            if (sU.checksign(sU.info(userName.getText(), userEmailSU.getText(), passStr, ques.getText(), ans.getText()))) {
                    try {
                        Inbox in = new Inbox();
                        String array[] = {userName.getText(), passStr, userEmailSU.getText(), ques.getText(), ans.getText()};
                        in.user = array;
                        in.setVisible(true);
                        in.setLocationRelativeTo(null);
                        this.dispose();
                    } catch (IOException ex) {
                        Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                    }
            } else {
                jLabel2.setText("UserName or Email already used");
            }
            } else {
                    jLabel2.setText("Email must have the domain \"@yallamail.com\"");
                }
        }
    }//GEN-LAST:event_signUpbtnMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        UserManual um = new UserManual();
        um.setVisible(true);
        um.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void credits1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_credits1MouseClicked
        creditsCount++;
        if (creditsCount % 2 == 1) {
            jPanel1.setVisible(true);
        } else {
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_credits1MouseClicked

    private void userManualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userManualMouseClicked
        UserManual um = new UserManual();
        um.setVisible(true);
        um.setLocationRelativeTo(null);
    }//GEN-LAST:event_userManualMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        creditsCount++;
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void creditsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditsMouseClicked
        creditsCount++;
        if (creditsCount % 2 == 1) {
            jPanel1.setVisible(true);
        } else {
            jPanel1.setVisible(false);
        }
    }//GEN-LAST:event_creditsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ans;
    private javax.swing.JLabel backgroundSI;
    private javax.swing.JLabel backgroundSU;
    private javax.swing.JLabel close1;
    private javax.swing.JLabel close2;
    private javax.swing.JLabel credits;
    private javax.swing.JLabel credits1;
    private javax.swing.JLabel dragFrame;
    private javax.swing.JLabel dragFrame1;
    private javax.swing.JLabel forgetPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logInPanel;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel minimize1;
    private javax.swing.JPasswordField passwordSI;
    private javax.swing.JPasswordField passwordSU;
    private javax.swing.JTextField ques;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signUpbtn;
    private javax.swing.JLabel toLogin;
    private javax.swing.JLabel toSignUp;
    private javax.swing.JTextField userEmailSI;
    private javax.swing.JTextField userEmailSU;
    private javax.swing.JLabel userManual;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
