/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailapp.gui;

import mailapp.logicCode.ForgetPassword;

/**
 *
 * @author محمد
 */
public class QuestionAndAnswer extends javax.swing.JFrame {

    /**
     * Creates new form QuestionAndAnswer
     */
    int xm;
    int ym;
    //public static String[] data;

    public QuestionAndAnswer() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Answer = new javax.swing.JTextField();
        Question = new javax.swing.JTextField();
        showpb = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bachground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Answer.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        Answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Answer.setBorder(null);
        Answer.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Answer.setOpaque(false);
        getContentPane().add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 280, 529, 81));

        Question.setEditable(false);
        Question.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        Question.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Question.setBorder(null);
        Question.setOpaque(false);
        getContentPane().add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 114, 529, 81));

        showpb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showpb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showpbMouseClicked(evt);
            }
        });
        getContentPane().add(showpb, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 397, 168, 92));

        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(646, 10, 18, 25));

        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 10, 17, 25));

        bar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barMouseDragged(evt);
            }
        });
        bar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barMousePressed(evt);
            }
        });
        getContentPane().add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 40));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 250, 60));

        bachground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/showPass.jpg"))); // NOI18N
        getContentPane().add(bachground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showpbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showpbMouseClicked
        ForgetPassword fp = new ForgetPassword();
        ForgetPasswordFrame f = new ForgetPasswordFrame();
        if (fp.answer(Answer.getText(), f.data)) {
            Showpasswordframe s = new Showpasswordframe();
            this.dispose();
            s.setVisible(true);
            s.setLocationRelativeTo(null);
        } else {
            jLabel3.setText("WRONG ANSWER");
        }

    }//GEN-LAST:event_showpbMouseClicked

    private void barMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xm, y - ym);
    }//GEN-LAST:event_barMouseDragged

    private void barMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barMousePressed
        // TODO add your handling code here:
        xm = evt.getX();
        ym = evt.getY();
    }//GEN-LAST:event_barMousePressed

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(QuestionAndAnswer.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionAndAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionAndAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionAndAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionAndAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionAndAnswer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Answer;
    public static javax.swing.JTextField Question;
    private javax.swing.JLabel bachground;
    private javax.swing.JLabel bar;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel showpb;
    // End of variables declaration//GEN-END:variables
}
