/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mailapp.gui;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import linkedList.cs45_cs23.LinkedList;
import static mailapp.gui.Inbox.attachments;
import static mailapp.gui.Inbox.jTextArea1;
import static mailapp.gui.Inbox.recieversNames;
import static mailapp.gui.Inbox.subjectCompose1;
import mailapp.logicCode.ComposeGUI;
import mailapp.logicCode.FilterSubject;
import mailapp.logicCode.Mail;
import mailapp.logicCode.SubtractDays;

/**
 *
 * @author HP
 */
public class ShowMessage extends javax.swing.JFrame {

    /**
     * Creates new form ShowMessage
     */
    LinkedList openAttatchments = new LinkedList();
public static String currentu;
public static String messageshown;
public static Mail currentmail=new Mail();
Inbox in1;
    public ShowMessage(LinkedList x,Mail m,String msg,String currentuser,JFrame in) {
        initComponents();
        showmail.setBackground(new Color(0, 0, 0, 0));
        in1=(Inbox)in;
        jScrollPane1.setBackground(new Color(0, 0, 0, 0));
        jScrollPane1.getViewport().setBackground(new Color(0, 0, 0, 0));
        tofromtext.setBackground(new Color(0, 0, 0, 0));
        subjectshow.setBackground(new Color(0, 0, 0, 0));
        messageshown=msg;
        currentu=currentuser;
        openAttatchments = x;
        currentmail=m;
    }
    private ShowMessage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        toorfrom = new javax.swing.JLabel();
        subjectshow = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        showmail = new javax.swing.JTextArea();
        tofromtext = new javax.swing.JTextField();
        attach1 = new javax.swing.JLabel();
        attach2 = new javax.swing.JLabel();
        attach3 = new javax.swing.JLabel();
        attach4 = new javax.swing.JLabel();
        attach5 = new javax.swing.JLabel();
        attach6 = new javax.swing.JLabel();
        na1 = new javax.swing.JLabel();
        na2 = new javax.swing.JLabel();
        na3 = new javax.swing.JLabel();
        na4 = new javax.swing.JLabel();
        na5 = new javax.swing.JLabel();
        na6 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        compose = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toorfrom.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        toorfrom.setForeground(new java.awt.Color(255, 255, 255));
        toorfrom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        toorfrom.setEnabled(false);
        jPanel1.add(toorfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 50, 100, 40));

        subjectshow.setEditable(false);
        subjectshow.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        subjectshow.setForeground(new java.awt.Color(255, 255, 255));
        subjectshow.setBorder(null);
        subjectshow.setOpaque(false);
        jPanel1.add(subjectshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 150, 430, 69));

        jScrollPane1.setBorder(null);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setOpaque(false);

        showmail.setEditable(false);
        showmail.setColumns(20);
        showmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        showmail.setForeground(new java.awt.Color(255, 255, 255));
        showmail.setLineWrap(true);
        showmail.setRows(5);
        showmail.setBorder(null);
        showmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        showmail.setFocusable(false);
        showmail.setHighlighter(null);
        showmail.setOpaque(false);
        jScrollPane1.setViewportView(showmail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 265, 430, 230));

        tofromtext.setEditable(false);
        tofromtext.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        tofromtext.setForeground(new java.awt.Color(255, 255, 255));
        tofromtext.setBorder(null);
        tofromtext.setOpaque(false);
        tofromtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tofromtextActionPerformed(evt);
            }
        });
        jPanel1.add(tofromtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 42, 430, 69));

        attach1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach1MouseClicked(evt);
            }
        });
        jPanel1.add(attach1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 110, 70));

        attach2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach2MouseClicked(evt);
            }
        });
        jPanel1.add(attach2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 110, 70));

        attach3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach3MouseClicked(evt);
            }
        });
        jPanel1.add(attach3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 520, 110, 70));

        attach4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach4MouseClicked(evt);
            }
        });
        jPanel1.add(attach4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 110, 70));

        attach5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach5MouseClicked(evt);
            }
        });
        jPanel1.add(attach5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 110, 70));

        attach6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attach6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attach6MouseClicked(evt);
            }
        });
        jPanel1.add(attach6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, 110, 70));

        na1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 110, 15));

        na2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 110, 15));

        na3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 110, 15));

        na4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 710, 110, 15));

        na5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 710, 110, 15));

        na6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(na6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 710, 110, 15));

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 760, 95, 42));

        compose.setBackground(new java.awt.Color(51, 51, 51));
        compose.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        compose.setForeground(new java.awt.Color(255, 255, 255));
        compose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compose.setText("Compose");
        compose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        compose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        compose.setOpaque(true);
        compose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                composeMouseClicked(evt);
            }
        });
        jPanel1.add(compose, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 760, 100, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mailapp/gui/showMessage.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 820));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 820));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tofromtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tofromtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tofromtextActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void attach1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach1MouseClicked
        // TODO add your handling code here:

        try {
            Desktop.getDesktop().open((File) openAttatchments.get(0));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_attach1MouseClicked

    private void attach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach2MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open((File) openAttatchments.get(1));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach2MouseClicked

    private void attach3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach3MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open((File) openAttatchments.get(2));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach3MouseClicked

    private void attach4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach4MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open((File) openAttatchments.get(3));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach4MouseClicked

    private void attach5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach5MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open((File) openAttatchments.get(4));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach5MouseClicked

    private void attach6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attach6MouseClicked
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open((File) openAttatchments.get(5));
        } catch (IOException ex) {
            Logger.getLogger(AddAttachmentFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attach6MouseClicked

    private void composeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_composeMouseClicked
      LinkedList reciNames=new LinkedList();
       String[] split=currentmail.rec.split("-");
        for(int kf=0;kf<split.length;kf++){
             reciNames.add((String)split[kf]);
          }
        ComposeGUI cG=new ComposeGUI();
        FilterSubject fs = new FilterSubject();
                        int names=0;
                        while(names!=reciNames.size()){
          try {
              if(fs.readFromFile(currentmail.subject,(String)reciNames.get(names))){
                  LinkedList name=new LinkedList();
                  name.add((String)reciNames.get(names));
                  fs.send(currentu, currentmail.subject, messageshown,currentmail.priority, name, openAttatchments,currentmail.attachBool);
              }
              else{
                  LinkedList name=new LinkedList();
                  name.add((String)reciNames.get(names));
                  cG.send(currentu, currentmail.subject, messageshown,currentmail.priority, name, openAttatchments,currentmail.attachBool);
              }
              names++;
          } catch (IOException ex) {
              Logger.getLogger(ShowMessage.class.getName()).log(Level.SEVERE, null, ex);
          }
                        }
        //ComposeGUI send1=new ComposeGUI();
        //send1.send(currentu, currentmail.subject, messageshown,currentmail.priority, reciNames, openAttatchments,currentmail.attachBool);
        
        SubtractDays rem=new SubtractDays();
        LinkedList recd=new LinkedList();
        recd.add((String)currentmail.subDate);
        try {
            rem.deleteMailDraft(recd, in1);
        } catch (IOException ex) {
            Logger.getLogger(ShowMessage.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
       // System.out.println(messageshown+" "+openAttatchments.size()+" "+currentu+" "+currentmail.rec);
//         messageshown=msg;
//        currentu=currentuser;
//        openAttatchments = x;
//        currentmail=m;
    }//GEN-LAST:event_composeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel attach1;
    public static javax.swing.JLabel attach2;
    public static javax.swing.JLabel attach3;
    public static javax.swing.JLabel attach4;
    public static javax.swing.JLabel attach5;
    public static javax.swing.JLabel attach6;
    private javax.swing.JLabel background;
    private javax.swing.JLabel close;
    public static javax.swing.JLabel compose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel na1;
    public static javax.swing.JLabel na2;
    public static javax.swing.JLabel na3;
    public static javax.swing.JLabel na4;
    public static javax.swing.JLabel na5;
    public static javax.swing.JLabel na6;
    public static javax.swing.JTextArea showmail;
    public static javax.swing.JTextField subjectshow;
    public static javax.swing.JTextField tofromtext;
    public static javax.swing.JLabel toorfrom;
    // End of variables declaration//GEN-END:variables
}
